name: Periodic Model Calibration

on: 
  schedule:
    - cron: '0 0 * * *'  #minutes, hours, day, month, day of week 

defaults:
  run:
    working-directory: Labs/Github_Labs/Lab2

permissions:
  contents: write

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate and Store Timestamp
      run: |
        timestamp=$(date '+%Y%m%d%H%M%S')
        echo "$timestamp" > timestamp.txt
      id: timestamp

    - name: Retrain Model
      run: |
        timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
        python ./src/train_model.py --timestamp "$timestamp"

    - name: Evaluate Model and Log Metrics
      run: |
        timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
        python ./src/evaluate_model.py --timestamp "$timestamp"

    - name: Commit and Push Changes
      run: |
        git config --global user.email "26876927+raminmohammadi@users.noreply.github.com"
        git config --global user.name "raminmohammadi"
        timestamp=$(cat timestamp.txt)
        metrics_filename="metrics/${timestamp}_metrics.json"
        model_filename="models/model_${timestamp}_dt_model.joblib"
        git add -f "$metrics_filename" "$model_filename"
        # Commit only if there are changes
        if ! git diff --cached --quiet; then
          git commit -m "Add metrics and updated model"
          git push
        else
          echo "No changes to commit."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



